### ISSUE TITLE
Add customizable time-to-live for verification codes

### ISSUE THREAD

**Issue by ac360** [serverless-components/passwordless#3]

**Comment by eahefnawy** [comment]
**UPDATE:** I've looked into dynamoDB TTL feature, and it partially solves our problem. The way it works is that it cleans up records based on a TTL settings, **however this clean up happens sometime within 48 hours**. That means if a user set a TTL of 5 mins (which is the default and what is common), it wouldn't be reliable for our use case.

So instead, I've added a customizable TTL config as inputs to the component, and I'm manually checking for expiration. I'm also manually removing verified codes from the database during the verify request.

For codes that are sent but never verified, they would still persist in the database but wouldn't be usable as they have likely expired. This is where DynamoDB TTL feature could come in handy to clean this up.

Anyway, I've opened a new [clean up old records](#4) issue, which depends on the dynamodb component to support that.
